
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEP = 4;
  public static final int LIT_INT = 34;
  public static final int INT = 23;
  public static final int PRINTLN = 26;
  public static final int LESS = 12;
  public static final int MINUS = 15;
  public static final int STATIC = 29;
  public static final int NOT = 13;
  public static final int AND = 11;
  public static final int LP = 7;
  public static final int COMMA = 3;
  public static final int CLASS = 19;
  public static final int RP = 8;
  public static final int PLUS = 16;
  public static final int ASSIGN = 17;
  public static final int MAIN = 24;
  public static final int IF = 22;
  public static final int THIS = 31;
  public static final int DOT = 2;
  public static final int EOF = 0;
  public static final int BOOLEAN = 18;
  public static final int LC = 5;
  public static final int LB = 9;
  public static final int RETURN = 28;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int RC = 6;
  public static final int RB = 10;
  public static final int IDENT = 36;
  public static final int VOID = 32;
  public static final int TIMES = 14;
  public static final int ELSE = 20;
  public static final int WHILE = 33;
  public static final int PUBLIC = 27;
  public static final int EXTENDS = 21;
  public static final int LIT_BOOL = 35;
  public static final int STRING = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOT",
  "COMMA",
  "SEP",
  "LC",
  "RC",
  "LP",
  "RP",
  "LB",
  "RB",
  "AND",
  "LESS",
  "NOT",
  "TIMES",
  "MINUS",
  "PLUS",
  "ASSIGN",
  "BOOLEAN",
  "CLASS",
  "ELSE",
  "EXTENDS",
  "IF",
  "INT",
  "MAIN",
  "NEW",
  "PRINTLN",
  "PUBLIC",
  "RETURN",
  "STATIC",
  "STRING",
  "THIS",
  "VOID",
  "WHILE",
  "LIT_INT",
  "LIT_BOOL",
  "IDENT"
  };
}

