
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 11;
  public static final int PARENTH_O = 4;
  public static final int MOD = 15;
  public static final int MAX = 8;
  public static final int ERROR = 10;
  public static final int PLUS = 12;
  public static final int EOF = 0;
  public static final int PARENTH_F = 5;
  public static final int NL = 6;
  public static final int ENTIER = 2;
  public static final int DIV = 14;
  public static final int COMMA = 9;
  public static final int error = 1;
  public static final int TIMES = 13;
  public static final int OPBIN = 3;
  public static final int MIN = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTIER",
  "OPBIN",
  "PARENTH_O",
  "PARENTH_F",
  "NL",
  "MIN",
  "MAX",
  "COMMA",
  "ERROR",
  "MINUS",
  "PLUS",
  "TIMES",
  "DIV",
  "MOD"
  };
}

