
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UNK = 16;
  public static final int WHILE = 10;
  public static final int IDENT = 4;
  public static final int PARENTHESE_F = 7;
  public static final int FOR = 11;
  public static final int ACC_F = 9;
  public static final int SEMI = 5;
  public static final int LITTERAL = 2;
  public static final int EQ = 14;
  public static final int EOF = 0;
  public static final int IF = 12;
  public static final int TYPE = 3;
  public static final int ELSE = 13;
  public static final int error = 1;
  public static final int PARENTHESE_O = 6;
  public static final int OPBIN = 15;
  public static final int ACC_O = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LITTERAL",
  "TYPE",
  "IDENT",
  "SEMI",
  "PARENTHESE_O",
  "PARENTHESE_F",
  "ACC_O",
  "ACC_F",
  "WHILE",
  "FOR",
  "IF",
  "ELSE",
  "EQ",
  "OPBIN",
  "UNK"
  };
}

